### ISSUE TITLE
Is it possible to get ban by sending requests to same endpoint repeatedly in range of 5-7 seconds?

### ISSUE THREAD

**Issue by samohovets** [stypr/clubhouse-py#1]
Thank you for your work!

I want to make a auto-updating subscriber counter in my bio, like "now i have N subscribers". As README says:
> Please note that you may get a permanent ban for sending invalid API requests. Server's ratelimit and security mechanisms are quite strict.

I just want to know it it's safe to do this. Have you ever been banned? If so, how often were the requests sent? I want to update my bio every 5-10 seconds. Is it safe?

**Comment by stypr** [comment]
Thanks for adding an issue.

>  Have you ever been banned? 

No. I didn't get banned but I see some people who were actually banned while testing the API.

Clubhouse has a rate-limit on their server-side code and the server actually returns a prior warning before they actually give a permanent ban.

It is always better to refrain from doing weird actions if you're not sure of what you're trying to do. What if someone sends you to your service every 5-10 seconds?

I have not tested how these ratelimits work, but it is very highly likely that you may get a ban.

As I mentioned in the README, the server's rate limit policy is quite strict and they've also implemented some security mechanisms to silently record all actions sent from the user.

I developed this to let people make their own build, not for the sake of making bots. Be careful of what you're trying tod o

**Comment by stypr** [comment]
Thanks for adding an issue.

>  Have you ever been banned? 

No. I didn't get banned until now but I've some people getting banned permanently from the Clubhouse by doing such actions.

As I mentioned, Clubhouse has ratelimits on their server-side code and the server actually returns a prior warning before they actually give you a permanent ban.

It is always better to refrain from doing weird actions if you're not sure of what you're trying to do. What if someone sends you such actions to your service every 5-10 seconds? Developers wouldn't have implemented the security mechanism if this wasn't their concern.

I have not tested how these ratelimits work by myself, but it is very highly likely that you may get a ban.

> Server's ratelimit and security mechanisms are quite strict.

As mentioned by other members while testing Clubhouse, the server's ratelimit policy is quite strict and it looks like developers have implemented some security mechanisms to silently record all actions sent from the user.

I developed this to let people make their own build for own use, not for the sake of making bots. Be careful of what you're trying to do.

**Comment by samohovets** [comment]
Thank you for your answer!
