### ISSUE TITLE
The room not available

### ISSUE THREAD

**Issue by myxomor** [stypr/clubhouse-py#10]
Hey! I try to connect to room with channel name from the link, but get that message:
`{'success': False, 'error_message': 'That room is no longer available 👋🏼\nTry starting a new one instead?'}`
And my friends with iOS can get access to that room. I don't understand why it happened.

**Comment by stypr** [comment]
There could be several reasons for this

1. You do not have enough permission to enter the channel
2. The channel works differently.

Ref. https://github.com/stypr/clubhouse-py/blob/v304/clubhouse.py#L501-L513

Try fixing the code to

```
client.join_channel(channel="channel_id", attribution_source="link")
```

**Comment by stypr** [comment]
Let me know if this has resolved your issue

**Comment by myxomor** [comment]
I applied these changes, but I can only connect to channels from the list

**Comment by stypr** [comment]
@myxomor 

The suggested step is the actual step that was directly taken from the Clubhouse app. If it didn't work, there is some other issue here.

**Comment by stypr** [comment]
I've tested this locally and it did work from my side. I guess there's something wrong from your side.

I checked how Android build has implemented this part and I see that there's no difference from my code.

https://github.com/grishka/Houseclub/blob/1.0.6/Houseclub/src/main/java/me/grishka/houseclub/MainActivity.java#L109-L138
https://github.com/grishka/Houseclub/blob/1.0.6/Houseclub/src/main/java/me/grishka/houseclub/MainActivity.java#L140-L165
https://github.com/grishka/Houseclub/blob/1.0.6/Houseclub/src/main/java/me/grishka/houseclub/api/methods/JoinChannel.java#L12

You also need to check if the channel contains `is_private` or `is_social_mode`. There are some channels that you may not have permissions to enter.

I will try to re-check if someone else suffers from the similar issue.
