### ISSUE TITLE
(OSX) Process is killed upon entering the channel

### ISSUE THREAD

**Issue by Peterprombutr** [stypr/clubhouse-py#11]
This has happened after I entered the channel code.
<img width="925" alt="Screen Shot 2021-02-21 at 20 25 05" src="https://user-images.githubusercontent.com/43899248/108626491-05b1ac80-7483-11eb-9e6e-47718f367de8.png">

**Comment by stypr** [comment]
I had the same issue.

You need to re-install the SDK again.
Please try re-installing the SDK until it works. I removed all existing installations and built the SDK manually from scratch.
