### ISSUE TITLE
req.json() is a weak point

### ISSUE THREAD

**Issue by yegorov-p** [stypr/clubhouse-py#16]
I really don't like the part with
```
req = requests.post(smth)
return req.json()
```
It can cause so many problems, server can return 50* and it will break .json() method, server can theoretically return "bad" json and so on.

What do you think about idea to at least start validating response headers, or (better!) check if server response is a correct JSON. I can make a PR if you approve the idea.

**Comment by stypr** [comment]
I will change it at some point. I think there are more serious things than this though.

**Comment by avg22980** [comment]
I didnt know what the hell i was doing. Go for it.
