### ISSUE TITLE
Can't enter the room

### ISSUE THREAD

**Issue by timurtokt** [stypr/clubhouse-py#18]
Hi, thanks for the work. After I launched the client and authorized by sms code and tried to enter a particular room the following error occurred:
```
zsh: killed     python3 cli.py
```
I think it has to do with permissions. Can you help?

**Comment by kirillkuzin** [comment]
Hi. Can you show your code ?

**Comment by stypr** [comment]
@ttoktassynov 

Duplicate issue.
https://github.com/stypr/clubhouse-py/issues/11
