### ISSUE TITLE
/get_event example?

### ISSUE THREAD

**Issue by yegorov-p** [stypr/clubhouse-py#6]
Hello!

Can anyone explain how **/get_event** method works? Let's say I have a link to event: https://www.joinclubhouse.com/event/abcdef 
I am trying to get link to the room from that event (yes, the event has already started and room exists). I thought that **abcdef** is an event_id, but calling .get_event(event_id='abcdef') returns 500 error from server.

**Comment by stypr** [comment]
I've re-analyzed this just now.

You can try `client.get_event(event_id=None, event_hashid="abcdef")` instead.

**Comment by msizaky16** [comment]
how can i join channel room via link?
