### ISSUE TITLE
Kick from channel feature

### ISSUE THREAD

**Issue by salemgolemugoo** [stypr/clubhouse-py#8]
Is there any possibility to kick a user from a channel but allow him to rejoin? Or maybe is there any list of blocked users related to the channel?

**Comment by stypr** [comment]
The currently supported feature is `block_from_channel` that kicks the user and permanently disallows the user from accessing the channel. (There is no way to even unblock the user.)

afaik there is no feature to kick the user and still allow the user to re-join the channel.

https://github.com/stypr/clubhouse-py/blob/v304/clubhouse.py#L577-L587
